events {}

http {

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream py_server {
        # ip_hash; 
        server team_2_backend:8000;
    }
 
    server {
        listen 80;
        server_name localhost;

        client_max_body_size 20M;

        # 프론트엔드 (React build)
        root /app/build;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /py/ {
            proxy_pass http://py_server/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}